# Site
name: "Ang moh in the east"
title: "ANG MOH IN THE EAST"
description: "Coffee shops, bars, and hawkers of east coast"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: /ang-moh-in-the-east
google_analytics: 'UA-46278016-1'
disqus: 'angmohintheeast'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  steve:
    name: Steve
    display_name: Steve
    gravatar: cf91810848bf33dd747b975a4e677331
    email: maxhawes@gmail.com
    twitter: https://twitter.com/stevehawes
    description: "Author of ang moh in the east, a food blog about the east coast of Singapore."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

# Google maps
maps:
  google:
    api_key: AIzaSyAxXmBdFzVTKJmMWE19gx2TKN1HbfqqtlQ

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
