# Site
title: "Ang moh in the east"
description: "Blog about the kopitiams, hawkers, and bars of Singapore's east coast"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
google_analytics: 'UA-146477071-2'
disqus: 'angmohintheeast'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  steve:
    name: Steve
    display_name: Steve
    gravatar: cf91810848bf33dd747b975a4e677331
    email: steve.singkarpor@gmail.com
    twitter: https://twitter.com/stevehawes
    description: "Author of ang moh in the east, a food blog about the east coast of Singapore."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-compose
  - amp-jekyll
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 21
paginate_path: /page:num/
    
# Other
markdown: kramdown

# Google maps
maps:
  google:
    api_key: AIzaSyAxXmBdFzVTKJmMWE19gx2TKN1HbfqqtlQ

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-5689621814678122"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      categories:
      image:
      category:
      rating:
      author:
    posts:
      description:
      categories:
      image:
      featured: false
      hidden: false
      rating:
      author:
  auto_open: false

  exclude:
    - changelog.md
    - LICENSE.txt
    - README.md
    - Gemfile
    - Gemfile.lock]